class RandomInt
{
public:
	// returns a RandomInt object
	// int low is the lower bound for random number
	// int high is the upper bound for random number
	// implementation adapted from Walter's post at http://stackoverflow.com/questions/5008804/generating-random-integer-from-a-range
	RandomInt(int, int);
	// return the random integer generated by class RandomInt
	int getRandomInt();
private:
	// store the random number generated by class RandomInt
	int randInt;
};
